### PR TITLE
Apply for badge

### LINKED ISSUE #82: Build "In-Person Events" and "Virtual Events" Application forms
### **Current situation**

The application forms for both **in-person** and **virtual event** badging are currently located on a [separate website](https://chaoss.community/diversity-and-inclusion-badging/), causing users to navigate back and forth. 

### **Proposed Solution**
Integrate the application forms directly into the [badging website](https://badging.chaoss.community/event-badging). Users can access these forms through "Event Badging" under the "Apply for Badge" button located in the top right corner.

The design mockups for these integrated pages can be found [here]( https://www.figma.com/file/BG3gSZL2ukRqtTz5i94CGH/Project-Badging?type=design&node-id=5172-14887&mode=design&t=m9MsOhJlYgFrW0pq-4). This issue relates to #78

### **Benefits**
•  Streamlined User Experience: Users can seamlessly apply for badges without leaving the badging website, leading to a smoother and more engaging experience.
•  Enhanced Consistency: Integrating the forms aligns with the website's design and creates a more cohesive user journey.

### PR DESCRIPTION
**Pull request by mide358**

### CODE REVIEW

**Comment by kaxada** [comment]
@mide358 looks like the `next` buttons on the forms are not functional and the font is different from the website font. But I am still doing more testing

**Comment by mide358** [comment]
> @mide358 looks like the `next` buttons on the forms are not functional and the font is different from the website font. But I am still doing more testing

@kaxada the buttons will only work if the fields are filled

**Comment by mide358** [comment]
> > @mide358 looks like the `next` buttons on the forms are not functional and the font is different from the website font. But I am still doing more testing
> 
> @kaxada the buttons will only work if the fields are filled

Also for the first page, the website input field will only work if it starts with www.

**Comment by kaxada** [comment]
Ooh.. awesome

**Comment by kaxada** [comment]
@mide358 do you have an idea what happened to this branch. where did the commits go?

**Comment by mide358** [comment]
@kaxada What branch are you talking about?

**Comment by kaxada** [comment]
@mide358 there were some changes that where connected to designing the application forms for he event badging applications. It was [related to these designs](https://www.figma.com/file/BG3gSZL2ukRqtTz5i94CGH/Project-Badging?type=design&node-id=5172-14887&mode=design&t=YTaxwdWXG70L2qao-0). I am sure it was somewhere but somehow it disappeared.

**Pull request closed without merging**
