### PR TITLE
Event badging form setup

### PR DESCRIPTION
**Pull request by Kingscliq**
This issue is not a fix but a setup for issue #82, the following were added to the event badging project

1. Set up the page for event badging forms
2. Built out the TextField Component which is also reusable
3. Conditionally rendered the pages for the virtual and physical pages

@Ruth-ikegah  cc: @kaxada

### CODE REVIEW

**Comment by kaxada** [comment]
@Kingscliq always reference the issue you are fixing somewhere in the commits or the comment section here so that reviewers don't confuse implementations.

**Comment by Kingscliq** [comment]
> @Kingscliq always reference the issue you are fixing somewhere in the commits or the comment section here so that reviewers don't confuse implementations.

Hi @kaxada thanks for the feedback, how do I reference the issues, is there a template for that at the moment that I can look through

**Comment by Ruth-ikegah** [comment]
> > @Kingscliq always reference the issue you are fixing somewhere in the commits or the comment section here so that reviewers don't confuse implementations.
> 
> Hi @kaxada thanks for the feedback, how do I reference the issues, is there a template for that at the moment that I can look through



> > @Kingscliq always reference the issue you are fixing somewhere in the commits or the comment section here so that reviewers don't confuse implementations.
> 
> Hi @kaxada thanks for the feedback, how do I reference the issues, is there a template for that at the moment that I can look through

Hi @Kingscliq you use the description, "This issue fixes #issuenumber". We hope to create a template soon.

**Comment by Kingscliq** [comment]
> > > @Kingscliq always reference the issue you are fixing somewhere in the commits or the comment section here so that reviewers don't confuse implementations.
> > 
> > 
> > Hi @kaxada thanks for the feedback, how do I reference the issues, is there a template for that at the moment that I can look through
> 
> > > @Kingscliq always reference the issue you are fixing somewhere in the commits or the comment section here so that reviewers don't confuse implementations.
> > 
> > 
> > Hi @kaxada thanks for the feedback, how do I reference the issues, is there a template for that at the moment that I can look through
> 
> Hi @Kingscliq you use the description, "This issue fixes #issuenumber". We hope to create a template soon.


Oh thanks for the feedback @Ruth-ikegah  will do just that

**Review by kaxada — COMMENTED** [review]
@Kingscliq did you intend to have it look this way or it is still a work in progress?
image

**Comment by Kingscliq** [comment]
> @Kingscliq did you intend to have it look this way or it is still a work in progress? image

@kaxada It's a work in progress, working alongside @IsraelChidera on this issue

**Comment by Ruth-ikegah** [comment]
Hi @Kingscliq great work so far on this PR. However, a little challenge because another developer is currently assigned to #82 and has been working on it. I am so sorry about this. Usually the flow is before you take up an issue, you should check if it has assigned and if not you can ask to be assigned to it. 

Could you work on #89 or any other issues here not assigned to anyone?

I am sorry once again for the confusion. Let me know if you have any questions.

**Comment by Kingscliq** [comment]
> Hi @Kingscliq great work so far on this PR. However, a little challenge because another developer is currently assigned to #82 and has been working on it. I am so sorry about this. Usually the flow is before you take up an issue, you should check if it has assigned and if not you can ask to be assigned to it.
> 
> Could you work on #89 or any other issues here not assigned to anyone?
> 
> I am sorry once again for the confusion. Let me know if you have any questions.

Hi @Ruth-ikegah thanks for the clarity, is the developer you were speaking @IsraelChidera ? If it is, then we were working alongside on the issue, but if not, then it was a mistake from me. 

But no problem, I will start working on https://github.com/badging/badging/issues/89, I will tag you on it so I can be assigned

**Comment by Ruth-ikegah** [comment]
> > Hi @Kingscliq great work so far on this PR. However, a little challenge because another developer is currently assigned to #82 and has been working on it. I am so sorry about this. Usually the flow is before you take up an issue, you should check if it has assigned and if not you can ask to be assigned to it.
> > Could you work on #89 or any other issues here not assigned to anyone?
> > I am sorry once again for the confusion. Let me know if you have any questions.
> 
> Hi @Ruth-ikegah thanks for the clarity, is the developer you were speaking @IsraelChidera ? If it is, then we were working alongside on the issue, but if not, then it was a mistake from me.
> 
> But no problem, I will start working on #89, I will tag you on it so I can be assigned

Thanks for understanding @Kingscliq ! No the person is Mide. If you check the assigned section on #82. So sorry for the confusion too Chidera! @IsraelChidera you can pick other open issues too that are not assigned. I will go ahead to close this PR.

**Pull request closed without merging**
