### PR TITLE
worked on pages in src folder

### LINKED ISSUE #71: Code Cleaning
This issue is intended to clean up some aspects of the code. This issue focuses on;
- removing all the redundant code that was commented out

- commenting on the necessary code segments or lines

- change the casing  to match the following rules:
1. Variables and functions: CamelCase
2. Classes and constructors: PascalCase
3. Filenames, constants, and environment variables: Snake_case
4. HTML attributes and CSS class names: Kebab-case

While you are doing so, Please make sure your code never breaks in any way. Be sure to always be running the dev server

### PR DESCRIPTION
**Pull request by SylviaifyX**
@kaxada kindly review changes made on pages on src folder.

### CODE REVIEW

**Comment by kaxada** [comment]
@SylviaifyX this looks good already but the checks are failing due to unmatched files. check the build logs and see what to correct

**Comment by SylviaifyX** [comment]
Ok I will do thank

**Review by SylviaifyX — COMMENTED** [review]
@kaxada  kindly review changes

**Comment by SylviaifyX** [comment]
@kaxada please kindly review

**Comment by kaxada** [comment]
I triggered the tests and they showed some consistent errors. I am going to checkout your PR on my machine this weekend and sort them out. I'm sure it's file references

**Comment by SylviaifyX** [comment]
Ok await your response @kaxada

**Review by kaxada — APPROVED** [review]

**Pull request merged**
